apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ljoeltvo
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ljoeltvo:828a5f386692cbcde640a005d789d5869d52de44@sha256:5e6c794933428baea9c7221e57441c0443fa6e0fabb20a28b46e81b6dffe4244
        name: container-image  
